#!/bin/sh

set -eu

log() {
	if [ "${ENV2FILE_VERBOSE-}" = 1 ]; then
		echo >&2 "$1"
	fi
}

while [ "${1-}" ]; do
	case "$1" in
		-n|--no-clobber)
			ENV2FILE_NOCLOBBER=1
			;;
		-v|--verbose)
			ENV2FILE_VERBOSE=1
			;;
	esac
	shift
done

if [ -z "${ENV2FILE_CONTENT-}" ] && [ -z "${ENV2FILE_TO-}" ]; then
	log 'Both $ENV2FILE_CONTENT and $ENV2FILE_TO are empty. Do nothing.'
	exit
fi

if [ "${ENV2FILE_CONTENT-}" ] && [ -z "${ENV2FILE_TO-}" ]; then
	echo >&2 'ENV2FILE_CONTENT defined while ENV2FILE_TO not defined. Please specify environment variable ENV2FILE_TO for destination file.'
	exit 1
fi

mkdir -p "$(dirname "$ENV2FILE_TO")"

if [ "${ENV2FILE_NOCLOBBER-}" = 1 ] && [ -e "$ENV2FILE_TO" ]; then
	log '--no-clobber specified. Not overwriting existing file.'
	exit
fi

if [ -z "${ENV2FILE_CONTENT-}" ]; then
	log "Writing empty file $(realpath "$ENV2FILE_TO")"
fi

echo -n "${ENV2FILE_CONTENT-}" > "$ENV2FILE_TO"
log "Written to $(realpath "$ENV2FILE_TO")"
