#!/bin/sh

set -eu

log() {
	if [ "${ENV2FILE_VERBOSE-}" = 1 ]; then
		echo >&2 "$1"
	fi
}

if [ "${1-}" = "-v" ] || [ "${1-}" = "--verbose" ]; then
	ENV2FILE_VERBOSE=1
fi

if [ -z "${ENV2FILE_CONTENT-}" ] && [ -z "${ENV2FILE_TO-}" ]; then
	log 'Both $ENV2FILE_CONTENT and $ENV2FILE_TO are empty. Do nothing.'
	exit
fi

if [ "${ENV2FILE_CONTENT-}" ] && [ -z "${ENV2FILE_TO-}" ]; then
	echo >&2 'ENV2FILE_CONTENT defined while ENV2FILE_TO not defined. Please specify environment variable ENV2FILE_TO for destination file.'
	exit 1
fi

echo -n "$ENV2FILE_CONTENT" > "$ENV2FILE_TO"
log "Written to $ENV2FILE_TO"
